package grammar.Absyn; // Java Package generated by the BNF Converter.

public class ECall extends Exp {
  public final String id_;
  public final ListExp listexp_;

  public ECall(String p1, ListExp p2) { id_ = p1; listexp_ = p2; }

  public <R,A> R accept(grammar.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.ECall) {
      grammar.Absyn.ECall x = (grammar.Absyn.ECall)o;
      return this.id_.equals(x.id_) && this.listexp_.equals(x.listexp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.id_.hashCode())+this.listexp_.hashCode();
  }


}
