package grammar.Absyn; // Java Package generated by the BNF Converter.

public class EPDecr extends Exp {
  public final Exp exp_;

  public EPDecr(Exp p1) { exp_ = p1; }

  public <R,A> R accept(grammar.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.EPDecr) {
      grammar.Absyn.EPDecr x = (grammar.Absyn.EPDecr)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
