package grammar.Absyn; // Java Package generated by the BNF Converter.

public class EString extends Exp {
  public final String string_;

  public EString(String p1) { string_ = p1; }

  public <R,A> R accept(grammar.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.EString) {
      grammar.Absyn.EString x = (grammar.Absyn.EString)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
